"""add_knowledge_articles_table

Revision ID: 037460c51f01
Revises: 2c6187c448a9
Create Date: 2026-08-14 01:30:53.526954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '037460c51f01'
down_revision: Union[str, Sequence[str], None] = '2c6187c448a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_articles',
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_knowledge_articles_created_by_users')),
    sa.ForeignKeyConstraint(['firm_id'], ['law_firms.id'], name=op.f('fk_knowledge_articles_firm_id_law_firms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_articles'))
    )
    op.create_index(op.f('ix_knowledge_articles_firm_id'), 'knowledge_articles', ['firm_id'], unique=False)
    # ### end Alembic commands ###
    # NOTE: pre-existing signed_contracts/support_requests/templates index drift
    # intentionally stripped from this migration — see c70ad5778c25's note.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_articles_firm_id'), table_name='knowledge_articles')
    op.drop_table('knowledge_articles')
    # ### end Alembic commands ###
