"""add_firm_integrations_table

Revision ID: 2c0201c4be92
Revises: 4295e965322e
Create Date: 2026-08-14 01:38:24.174345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c0201c4be92'
down_revision: Union[str, Sequence[str], None] = '4295e965322e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firm_integrations',
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('SIGNINGHUB', 'TRACKADO', 'CONTRACT_EXPRESS', 'CLOUD_STORAGE', name='integrationprovider'), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('encrypted_credentials', sa.Text(), nullable=True),
    sa.Column('configured_by', sa.UUID(), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['configured_by'], ['users.id'], name=op.f('fk_firm_integrations_configured_by_users')),
    sa.ForeignKeyConstraint(['firm_id'], ['law_firms.id'], name=op.f('fk_firm_integrations_firm_id_law_firms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_firm_integrations')),
    sa.UniqueConstraint('firm_id', 'provider', name='uq_firm_integrations_firm_provider')
    )
    op.create_index(op.f('ix_firm_integrations_firm_id'), 'firm_integrations', ['firm_id'], unique=False)
    # ### end Alembic commands ###
    # NOTE: pre-existing signed_contracts/support_requests/templates index drift
    # intentionally stripped from this migration — see c70ad5778c25's note.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_firm_integrations_firm_id'), table_name='firm_integrations')
    op.drop_table('firm_integrations')
    # ### end Alembic commands ###
