"""add matters and matter_assignments tables

Revision ID: 4f0c9972a2fd
Revises: 84dbd02da9de
Create Date: 2026-07-09 22:48:28.498355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f0c9972a2fd'
down_revision: Union[str, Sequence[str], None] = '84dbd02da9de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matters',
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('INTAKE', 'IN_PROGRESS', 'CLOSED', name='matterstatus'), nullable=False),
    sa.Column('is_visible_to_client', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_matters_client_id_clients')),
    sa.ForeignKeyConstraint(['firm_id'], ['law_firms.id'], name=op.f('fk_matters_firm_id_law_firms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matters'))
    )
    op.create_table('matter_assignments',
    sa.Column('matter_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_on_matter', sa.Enum('LEAD_LAWYER', 'PARALEGAL', 'SECRETARY', 'REVIEWER', name='matterrole'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], name=op.f('fk_matter_assignments_matter_id_matters')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_matter_assignments_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matter_assignments'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matter_assignments')
    op.drop_table('matters')
    # ### end Alembic commands ###
