"""add actor and error detail to request logs

Revision ID: 52368daf64d8
Revises: b1c4a7e2f9d3
Create Date: 2026-08-06 23:10:59.620564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52368daf64d8'
down_revision: Union[str, Sequence[str], None] = 'b1c4a7e2f9d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_logs', sa.Column('actor_type', sa.String(length=20), nullable=True))
    op.add_column('request_logs', sa.Column('actor_id', sa.String(length=64), nullable=True))
    op.add_column('request_logs', sa.Column('error_detail', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request_logs', 'error_detail')
    op.drop_column('request_logs', 'actor_id')
    op.drop_column('request_logs', 'actor_type')
    # ### end Alembic commands ###
