"""add due_date to matters

Revision ID: 557017a424bb
Revises: 6d122af37665
Create Date: 2026-08-06 01:31:49.584078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '557017a424bb'
down_revision: Union[str, Sequence[str], None] = '6d122af37665'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matters', sa.Column('due_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matters', 'due_date')
    # ### end Alembic commands ###
