"""add support requests table

Revision ID: 701acd79994c
Revises: 414433b30918
Create Date: 2026-08-03 21:49:23.406940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '701acd79994c'
down_revision: Union[str, Sequence[str], None] = '414433b30918'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support_requests',
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('request_type', sa.Enum('NDA', 'CONSULTANCY', 'SUPPLIER', 'GENERAL', name='supportrequesttype'), nullable=False),
    sa.Column('counterparty', sa.String(length=200), nullable=True),
    sa.Column('priority', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='supportrequestpriority'), nullable=False),
    sa.Column('needed_by', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reference_documents', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', name='supportrequeststatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_support_requests_client_id_clients')),
    sa.ForeignKeyConstraint(['contact_id'], ['client_contacts.id'], name=op.f('fk_support_requests_contact_id_client_contacts')),
    sa.ForeignKeyConstraint(['firm_id'], ['law_firms.id'], name=op.f('fk_support_requests_firm_id_law_firms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_support_requests'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('support_requests')
    # ### end Alembic commands ###
