"""rename law_firm tenant to organization

Part of the corporate-pivot rebuild (see the plan): the tenant concept moves
from "law firm" to "organization" everywhere — models, columns, the RLS GUC
(app.current_firm_id -> app.current_org_id, see app/database/rls.py), and now
the schema itself.

Renaming a column/table in Postgres is transparent to dependent objects —
existing RLS policies, views, and FKs automatically follow the rename since
they're stored against object OIDs, not text. So this migration only needs
to rename things once; nothing downstream needs to be dropped and recreated.
Constraint/index names are renamed too, purely for readability of future
psql describe-table output and migrations — they'd keep working either way.

One thing table/column renames do NOT fix automatically: every RLS policy's
USING/WITH CHECK expression calls `current_setting('app.current_firm_id', ...)`
— that's a string literal (a GUC name), not a reference to the renamed column,
so Postgres has no dependency to follow and update. Since app/database/rls.py
now sets `app.current_org_id` instead, every policy has to be rewritten via
ALTER POLICY or it silently stops matching and every write starts failing RLS.

Revision ID: 7be238228b8e
Revises: b4c5d6e7f8a9
Create Date: 2026-09-15 01:37:13.621470

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '7be238228b8e'
down_revision: Union[str, Sequence[str], None] = 'b4c5d6e7f8a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Every table with a direct firm_id -> organizations FK, and whether it has
# the standard ix_<table>_firm_id index / fk_<table>_firm_id_law_firms FK
# constraint naming (all of them do, generated by Alembic's naming convention).
_TABLES_WITH_FIRM_ID = [
    "users", "clients", "matters", "templates", "signed_contracts", "audit_logs",
    "intake_forms", "intake_submissions", "knowledge_articles", "firm_integrations",
    "signature_requests", "fallback_clauses",
]

# audit_logs.firm_id has no FK constraint (audit rows intentionally outlive
# a deleted tenant) — every other table in the list above does.
_TABLES_WITHOUT_FK = {"audit_logs"}

# Every RLS-covered table (see the various add_*_rls migrations) — direct ones
# check their own org_id; indirect ones check a parent row's org_id via EXISTS.
_RLS_DIRECT_TABLES = [
    "audit_logs", "clients", "fallback_clauses", "org_integrations",
    "intake_forms", "intake_submissions", "knowledge_articles", "matters",
    "signature_requests", "signed_contracts", "templates",
]
_RLS_INDIRECT_TABLES = [
    ("intake_form_fields", "form_id", "intake_forms"),
    ("intake_submission_answers", "submission_id", "intake_submissions"),
    ("matter_approvals", "matter_id", "matters"),
    ("matter_assignments", "matter_id", "matters"),
    ("matter_contact_permissions", "matter_id", "matters"),
    ("matter_documents", "matter_id", "matters"),
    ("matter_messages", "matter_id", "matters"),
    ("matter_tasks", "matter_id", "matters"),
    ("signature_recipients", "signature_request_id", "signature_requests"),
]

_IS_OWNER = "current_setting('app.is_owner', true) = 'true'"
_CURRENT_ORG_ID = "NULLIF(current_setting('app.current_org_id', true), '')::uuid"
_CURRENT_FIRM_ID = "NULLIF(current_setting('app.current_firm_id', true), '')::uuid"


def _fix_rls_policies(current_org_expr: str) -> None:
    for table in _RLS_DIRECT_TABLES:
        op.execute(
            f"""
            ALTER POLICY tenant_isolation ON {table}
            USING ({_IS_OWNER} OR org_id = {current_org_expr})
            WITH CHECK ({_IS_OWNER} OR org_id = {current_org_expr})
            """
        )
    for table, fk_column, parent_table in _RLS_INDIRECT_TABLES:
        exists_clause = f"""
            EXISTS (
                SELECT 1 FROM {parent_table}
                WHERE {parent_table}.id = {table}.{fk_column}
                AND {parent_table}.org_id = {current_org_expr}
            )
        """
        op.execute(
            f"""
            ALTER POLICY tenant_isolation ON {table}
            USING ({_IS_OWNER} OR {exists_clause})
            WITH CHECK ({_IS_OWNER} OR {exists_clause})
            """
        )


def upgrade() -> None:
    for table in _TABLES_WITH_FIRM_ID:
        if table not in _TABLES_WITHOUT_FK:
            op.execute(f"ALTER TABLE {table} RENAME CONSTRAINT fk_{table}_firm_id_law_firms TO fk_{table}_org_id_organizations")
        op.execute(f"ALTER INDEX ix_{table}_firm_id RENAME TO ix_{table}_org_id")
        op.alter_column(table, "firm_id", new_column_name="org_id")

    # firm_integrations' extra composite unique constraint.
    op.execute("ALTER TABLE firm_integrations RENAME CONSTRAINT uq_firm_integrations_firm_provider TO uq_firm_integrations_org_provider")

    op.execute("ALTER TABLE law_firms RENAME CONSTRAINT pk_law_firms TO pk_organizations")
    op.rename_table("law_firms", "organizations")

    # Matches the model rename (FirmIntegration -> OrganizationIntegration);
    # do this last so the constraint/index renames above (which reference the
    # table by its old name) already landed.
    op.execute("ALTER INDEX ix_firm_integrations_org_id RENAME TO ix_org_integrations_org_id")
    op.execute("ALTER TABLE firm_integrations RENAME CONSTRAINT uq_firm_integrations_org_provider TO uq_org_integrations_org_provider")
    op.execute("ALTER TABLE firm_integrations RENAME CONSTRAINT fk_firm_integrations_org_id_organizations TO fk_org_integrations_org_id_organizations")
    op.rename_table("firm_integrations", "org_integrations")

    _fix_rls_policies(_CURRENT_ORG_ID)


def downgrade() -> None:
    _fix_rls_policies(_CURRENT_FIRM_ID)

    op.rename_table("org_integrations", "firm_integrations")
    op.execute("ALTER TABLE firm_integrations RENAME CONSTRAINT fk_org_integrations_org_id_organizations TO fk_firm_integrations_org_id_organizations")
    op.execute("ALTER TABLE firm_integrations RENAME CONSTRAINT uq_org_integrations_org_provider TO uq_firm_integrations_org_provider")
    op.execute("ALTER INDEX ix_org_integrations_org_id RENAME TO ix_firm_integrations_org_id")

    op.rename_table("organizations", "law_firms")
    op.execute("ALTER TABLE law_firms RENAME CONSTRAINT pk_organizations TO pk_law_firms")

    op.execute("ALTER TABLE firm_integrations RENAME CONSTRAINT uq_firm_integrations_org_provider TO uq_firm_integrations_firm_provider")

    for table in reversed(_TABLES_WITH_FIRM_ID):
        op.alter_column(table, "org_id", new_column_name="firm_id")
        op.execute(f"ALTER INDEX ix_{table}_org_id RENAME TO ix_{table}_firm_id")
        if table not in _TABLES_WITHOUT_FK:
            op.execute(f"ALTER TABLE {table} RENAME CONSTRAINT fk_{table}_org_id_organizations TO fk_{table}_firm_id_law_firms")
