"""add_signature_requests_and_recipients_tables

Revision ID: 86d45629cb53
Revises: 96c99cb1e4f9
Create Date: 2026-08-15 22:29:17.687298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM as PG_ENUM


# revision identifiers, used by Alembic.
revision: str = '86d45629cb53'
down_revision: Union[str, Sequence[str], None] = '96c99cb1e4f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signature_requests',
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('matter_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'DECLINED', 'VOIDED', name='signaturerequeststatus'), nullable=False),
    sa.Column('documenso_document_id', sa.String(length=100), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signed_contract_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_signature_requests_client_id_clients')),
    sa.ForeignKeyConstraint(['firm_id'], ['law_firms.id'], name=op.f('fk_signature_requests_firm_id_law_firms')),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], name=op.f('fk_signature_requests_matter_id_matters')),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_signature_requests_requested_by_users')),
    sa.ForeignKeyConstraint(['signed_contract_id'], ['signed_contracts.id'], name=op.f('fk_signature_requests_signed_contract_id_signed_contracts')),
    sa.ForeignKeyConstraint(['source_document_id'], ['matter_documents.id'], name=op.f('fk_signature_requests_source_document_id_matter_documents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signature_requests'))
    )
    op.create_index(op.f('ix_signature_requests_client_id'), 'signature_requests', ['client_id'], unique=False)
    op.create_index(op.f('ix_signature_requests_documenso_document_id'), 'signature_requests', ['documenso_document_id'], unique=False)
    op.create_index(op.f('ix_signature_requests_firm_id'), 'signature_requests', ['firm_id'], unique=False)
    op.create_index(op.f('ix_signature_requests_matter_id'), 'signature_requests', ['matter_id'], unique=False)
    op.create_table('signature_recipients',
    sa.Column('signature_request_id', sa.UUID(), nullable=False),
    # PG_ENUM(..., create_type=False): the `recipienttype` enum already exists in the
    # database (created by the notifications table's migration) — this column reuses
    # it rather than defining a second, separate Postgres type of the same name.
    # (The generic sa.Enum(..., create_type=False) does NOT suppress the CREATE TYPE
    # DDL here — only the postgres-dialect-specific ENUM class honors that flag.)
    sa.Column('recipient_type', PG_ENUM('STAFF', 'CLIENT_CONTACT', name='recipienttype', create_type=False), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('signing_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SIGNED', 'DECLINED', name='signaturerecipientstatus'), nullable=False),
    sa.Column('signing_url', sa.String(length=1000), nullable=False),
    sa.Column('documenso_recipient_id', sa.String(length=100), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['signature_request_id'], ['signature_requests.id'], name=op.f('fk_signature_recipients_signature_request_id_signature_requests')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signature_recipients'))
    )
    op.create_index(op.f('ix_signature_recipients_signature_request_id'), 'signature_recipients', ['signature_request_id'], unique=False)
    # ### end Alembic commands ###
    # NOTE: autogenerate also detected 3 pre-existing index drops on unrelated tables
    # (signed_contracts/support_requests/templates firm_id indexes) — that's schema
    # drift that predates this migration, not something this change should touch, so
    # those ops were intentionally left out here.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signature_recipients_signature_request_id'), table_name='signature_recipients')
    op.drop_table('signature_recipients')
    op.drop_index(op.f('ix_signature_requests_matter_id'), table_name='signature_requests')
    op.drop_index(op.f('ix_signature_requests_firm_id'), table_name='signature_requests')
    op.drop_index(op.f('ix_signature_requests_documenso_document_id'), table_name='signature_requests')
    op.drop_index(op.f('ix_signature_requests_client_id'), table_name='signature_requests')
    op.drop_table('signature_requests')
    # ### end Alembic commands ###
    # recipienttype is intentionally not dropped here — it's shared with the
    # notifications table, created by an earlier migration.
    sa.Enum(name='signaturerecipientstatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='signaturerequeststatus').drop(op.get_bind(), checkfirst=True)
