"""add matter documents table

Revision ID: 986f46fa7748
Revises: a62607c2daa3
Create Date: 2026-07-27 01:30:17.550973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '986f46fa7748'
down_revision: Union[str, Sequence[str], None] = 'a62607c2daa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matter_documents',
    sa.Column('matter_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('file_key', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], name=op.f('fk_matter_documents_matter_id_matters')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_matter_documents_uploaded_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matter_documents'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matter_documents')
    # ### end Alembic commands ###
