"""add signed contracts table

Revision ID: b1e993708ad7
Revises: 52368daf64d8
Create Date: 2026-08-06 23:51:21.389010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1e993708ad7'
down_revision: Union[str, Sequence[str], None] = '52368daf64d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signed_contracts',
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('matter_id', sa.UUID(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('agreement_type', sa.Enum('NDA', 'CONSULTANCY', 'SUPPLIER', 'GENERAL', name='contracttype'), nullable=False),
    sa.Column('signed_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('integration_source', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', name='contractstatus'), nullable=False),
    sa.Column('file_key', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_signed_contracts_client_id_clients')),
    sa.ForeignKeyConstraint(['firm_id'], ['law_firms.id'], name=op.f('fk_signed_contracts_firm_id_law_firms')),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], name=op.f('fk_signed_contracts_matter_id_matters')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_signed_contracts_uploaded_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signed_contracts'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signed_contracts')
    # ### end Alembic commands ###
    sa.Enum(name='contractstatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='contracttype').drop(op.get_bind(), checkfirst=True)
