"""add_intake_tables

Revision ID: c70ad5778c25
Revises: d4b2e6f18a3c
Create Date: 2026-08-14 01:27:28.740182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c70ad5778c25'
down_revision: Union[str, Sequence[str], None] = 'd4b2e6f18a3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intake_forms',
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_intake_forms_created_by_users')),
    sa.ForeignKeyConstraint(['firm_id'], ['law_firms.id'], name=op.f('fk_intake_forms_firm_id_law_firms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_intake_forms'))
    )
    op.create_index(op.f('ix_intake_forms_firm_id'), 'intake_forms', ['firm_id'], unique=False)
    op.create_table('intake_form_fields',
    sa.Column('form_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('field_type', sa.Enum('TEXT', 'TEXTAREA', 'NUMBER', 'DATE', 'DROPDOWN', 'CHECKBOX', 'FILE', name='intakefieldtype'), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('help_text', sa.String(length=500), nullable=True),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['intake_forms.id'], name=op.f('fk_intake_form_fields_form_id_intake_forms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_intake_form_fields'))
    )
    op.create_index(op.f('ix_intake_form_fields_form_id'), 'intake_form_fields', ['form_id'], unique=False)
    op.create_table('intake_submissions',
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('form_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'IN_REVIEW', 'CONVERTED', 'DECLINED', name='intakesubmissionstatus'), nullable=False),
    sa.Column('converted_matter_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_intake_submissions_client_id_clients')),
    sa.ForeignKeyConstraint(['contact_id'], ['client_contacts.id'], name=op.f('fk_intake_submissions_contact_id_client_contacts')),
    sa.ForeignKeyConstraint(['converted_matter_id'], ['matters.id'], name=op.f('fk_intake_submissions_converted_matter_id_matters')),
    sa.ForeignKeyConstraint(['firm_id'], ['law_firms.id'], name=op.f('fk_intake_submissions_firm_id_law_firms')),
    sa.ForeignKeyConstraint(['form_id'], ['intake_forms.id'], name=op.f('fk_intake_submissions_form_id_intake_forms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_intake_submissions'))
    )
    op.create_index(op.f('ix_intake_submissions_firm_id'), 'intake_submissions', ['firm_id'], unique=False)
    op.create_index(op.f('ix_intake_submissions_form_id'), 'intake_submissions', ['form_id'], unique=False)
    op.create_table('intake_submission_answers',
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('field_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('file_key', sa.String(length=500), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['intake_form_fields.id'], name=op.f('fk_intake_submission_answers_field_id_intake_form_fields')),
    sa.ForeignKeyConstraint(['submission_id'], ['intake_submissions.id'], name=op.f('fk_intake_submission_answers_submission_id_intake_submissions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_intake_submission_answers'))
    )
    op.create_index(op.f('ix_intake_submission_answers_submission_id'), 'intake_submission_answers', ['submission_id'], unique=False)
    # ### end Alembic commands ###
    # NOTE: autogenerate also proposed dropping ix_signed_contracts_firm_id /
    # ix_support_requests_firm_id / ix_templates_firm_id here — that's pre-existing
    # drift (those indexes were added via raw SQL in d4b2e6f18a3c and were never
    # declared with index=True on the models), unrelated to this migration. Removed
    # from both directions intentionally; do not re-add via autogenerate.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_intake_submission_answers_submission_id'), table_name='intake_submission_answers')
    op.drop_table('intake_submission_answers')
    op.drop_index(op.f('ix_intake_submissions_form_id'), table_name='intake_submissions')
    op.drop_index(op.f('ix_intake_submissions_firm_id'), table_name='intake_submissions')
    op.drop_table('intake_submissions')
    op.drop_index(op.f('ix_intake_form_fields_form_id'), table_name='intake_form_fields')
    op.drop_table('intake_form_fields')
    op.drop_index(op.f('ix_intake_forms_firm_id'), table_name='intake_forms')
    op.drop_table('intake_forms')
    # ### end Alembic commands ###
