"""generalize notifications to clients and add matter messages

Revision ID: fe1889c44bf3
Revises: 557017a424bb
Create Date: 2026-08-06 01:52:23.026014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe1889c44bf3'
down_revision: Union[str, Sequence[str], None] = '557017a424bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matter_messages',
    sa.Column('matter_id', sa.UUID(), nullable=False),
    sa.Column('author_type', sa.Enum('STAFF', 'CLIENT_CONTACT', name='messageauthortype'), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('author_name', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['matter_id'], ['matters.id'], name=op.f('fk_matter_messages_matter_id_matters')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matter_messages'))
    )
    op.create_index(op.f('ix_matter_messages_matter_id'), 'matter_messages', ['matter_id'], unique=False)
    # add_column (unlike create_table) doesn't auto-create a new Enum type, so it must be created explicitly first
    recipient_type_enum = sa.Enum('STAFF', 'CLIENT_CONTACT', name='recipienttype')
    recipient_type_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('notifications', sa.Column('recipient_type', recipient_type_enum, nullable=False))
    op.add_column('notifications', sa.Column('recipient_id', sa.UUID(), nullable=False))
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.create_index(op.f('ix_notifications_recipient_id'), 'notifications', ['recipient_id'], unique=False)
    op.drop_constraint(op.f('fk_notifications_user_id_users'), 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_notifications_user_id_users'), 'notifications', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_notifications_recipient_id'), table_name='notifications')
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.drop_column('notifications', 'recipient_id')
    op.drop_column('notifications', 'recipient_type')
    sa.Enum(name='recipienttype').drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f('ix_matter_messages_matter_id'), table_name='matter_messages')
    op.drop_table('matter_messages')
    # ### end Alembic commands ###
